### ISSUE TITLE
Integration tests for the charms are failing: Configuration file ~/.kube/config not found

### ISSUE THREAD

**Issue by mvlassis** [canonical/bundle-kubeflow#1093]
### Bug Description

The CI for multiple of our repositories is failing on the integration tests, with the same error:
```
lightkube.core.exceptions.ConfigError: Configuration file ~/.kube/config not found
```

Some example runs can be found [here](https://github.com/canonical/kubeflow-tensorboards-operator/actions/runs/11031322782/job/30638646317?pr=143), [here](https://github.com/canonical/kfp-operators/actions/runs/11029099139/job/30640088643?pr=572), and [here](https://github.com/canonical/envoy-operator/actions/runs/11029068911/job/30640000215).

I believe the error is due to [this commit](https://github.com/charmed-kubernetes/actions-operator/issues/84) in the charmed-kubernetes actions. Reverting to the previous commit results in all the workflows successfully running.

### To Reproduce

- Create a PR to trigger the CI in one of our repositories.
- View the results of the Integration test.

### Environment

`charmed-kubernetes/actions-operator` repo: `main` branch

### Relevant Log Output

```shell
__________________ ERROR at setup of test_create_tensorboard ___________________
Traceback (most recent call last):
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/lightkube/config/kubeconfig.py", line 175, in from_service_account
    token = account_dir.joinpath("token").read_text()
  File "/usr/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/lightkube/config/kubeconfig.py", line 210, in from_env
    return KubeConfig.from_service_account(service_account=service_account)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/lightkube/config/kubeconfig.py", line 178, in from_service_account
    raise exceptions.ConfigError(str(e))
lightkube.core.exceptions.ConfigError: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 241, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/unraisableexception.py", line 85, in pytest_runtest_setup
    yield from unraisable_exception_runtest_hook()
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/unraisableexception.py", line 65, in unraisable_exception_runtest_hook
    yield
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/logging.py", line 844, in pytest_runtest_setup
    yield from self._runtest_for(item, "setup")
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/logging.py", line 833, in _runtest_for
    yield
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/capture.py", line 873, in pytest_runtest_setup
    return (yield)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/threadexception.py", line 82, in pytest_runtest_setup
    yield from thread_exception_runtest_hook()
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/threadexception.py", line 63, in thread_exception_runtest_hook
    yield
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 159, in pytest_runtest_setup
    item.session._setupstate.setup(item)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 517, in setup
    raise exc
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 514, in setup
    col.setup()
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/python.py", line 1635, in setup
    self._request._fillfixtures()
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/fixtures.py", line 686, in _fillfixtures
    item.funcargs[argname] = self.getfixturevalue(argname)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/fixtures.py", line 521, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/fixtures.py", line 606, in _get_active_fixturedef
    fixturedef.execute(request=subrequest)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/fixtures.py", line 1076, in execute
    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 182, in _multicall
    return outcome.get_result()
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/setuponly.py", line 36, in pytest_fixture_setup
    return (yield)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/fixtures.py", line 1125, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/_pytest/fixtures.py", line 880, in call_fixture_func
    fixture_result = next(generator)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/charms/tensorboard-controller/tests/integration/test_charm.py", line 52, in create_tensorboard
    lightkube_client = Client()
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/lightkube/core/client.py", line 43, in __init__
    self._client = GenericSyncClient(config, namespace=namespace, timeout=timeout, lazy=lazy,
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/lightkube/core/generic_client.py", line 82, in __init__
    config = KubeConfig.from_env().get()
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/lightkube/config/kubeconfig.py", line 212, in from_env
    return KubeConfig.from_file(os.environ.get('KUBECONFIG', default_config))
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/lightkube/config/kubeconfig.py", line 142, in from_file
    raise exceptions.ConfigError(f"Configuration file {fname} not found")
lightkube.core.exceptions.ConfigError: Configuration file ~/.kube/config not found
```

**Comment by mvlassis** [comment]
Closing this issue as it has been swiftly fixed in this PR: https://github.com/charmed-kubernetes/actions-operator/issues/84. :)
