### ISSUE TITLE
kubeflow Issue in istio-pilot-0: hook failed: "istio-pilot-relation-created"

### ISSUE THREAD

**Issue by Nickhil215** [canonical/bundle-kubeflow#1190]
### Bug Description

Hi,

I have deployed kubeflow 1.9 using juju on kind kubernatives [:~$ kubectl version --- Client Version: v1.31.0 Kustomize Version: v5.4.2 Server Version: v1.31.0  on my laptop running Ubuntu 22.04. The istio-pilot pod is showing following errors. Other services are in a waiting state probably because this issue 

Readiness probe failed: HTTP probe failed with statuscode: 502

### To Reproduce

1. kubectl config view --raw | juju add-k8s myk8scloud --cluster-name=kind-kubeflow --client
2. juju add-model kubeflow
3.  sudo sysctl fs.inotify.max_user_instances=1280
sudo sysctl fs.inotify.max_user_watches=655360
4. juju deploy ch:kubeflow --trust --channel=1.9/stable
5. juju status
![image](https://github.com/user-attachments/assets/92957f6a-18e4-4445-993f-d30876e900ee)

### Environment

I'm using kind on my ubuntu laptopUbuntu

### Relevant Log Output

```shell
pod logs ::

2024-12-17T11:46:20.302Z [pebble] Check "readiness" failure 49 (threshold 3): received non-20x status code 418
2024-12-17T11:46:30.302Z [pebble] Check "readiness" failure 50 (threshold 3): received non-20x status code 418
2024-12-17T11:46:40.302Z [pebble] Check "readiness" failure 51 (threshold 3): received non-20x status code 418
2024-12-17T11:46:50.304Z [pebble] Check "readiness" failure 52 (threshold 3): received non-20x status code 418
2024-12-17T11:46:57.119Z [container-agent] 2024-12-17 11:46:57 INFO juju.worker.uniter resolver.go:180 awaiting error resolution for "relation-created" hook
2024-12-17T11:46:58.595Z [container-agent] 2024-12-17 11:46:58 INFO juju-log istio-pilot:20: HTTP Request: GET https://10.96.0.1/api/v1/namespaces/kubeflow/services/istio-ingressgateway-workload "HTTP/1.1 200 OK"
2024-12-17T11:46:58.668Z [container-agent] 2024-12-17 11:46:58 ERROR juju-log istio-pilot:20: Uncaught exception while in charm code:
2024-12-17T11:46:58.668Z [container-agent] Traceback (most recent call last):
2024-12-17T11:46:58.668Z [container-agent]   File "./src/charm.py", line 1209, in <module>
2024-12-17T11:46:58.668Z [container-agent]     main(Operator)
2024-12-17T11:46:58.668Z [container-agent]   File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 549, in main
2024-12-17T11:46:58.668Z [container-agent]     manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
2024-12-17T11:46:58.668Z [container-agent]   File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 432, in __init__
2024-12-17T11:46:58.668Z [container-agent]     self.charm = self._make_charm(self.framework, self.dispatcher)
2024-12-17T11:46:58.668Z [container-agent]   File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 435, in _make_charm
2024-12-17T11:46:58.668Z [container-agent]     charm = self._charm_class(framework)
2024-12-17T11:46:58.668Z [container-agent]   File "./src/charm.py", line 115, in __init__
2024-12-17T11:46:58.668Z [container-agent]     cert_subject=self._cert_subject,
2024-12-17T11:46:58.668Z [container-agent]   File "./src/charm.py", line 476, in _cert_subject
2024-12-17T11:46:58.668Z [container-agent]     svc_address = _get_gateway_address_from_svc(svc)
2024-12-17T11:46:58.668Z [container-agent]   File "./src/charm.py", line 1063, in _get_gateway_address_from_svc
2024-12-17T11:46:58.668Z [container-agent]     gateway_address = _get_address_from_loadbalancer(svc)
2024-12-17T11:46:58.668Z [container-agent]   File "./src/charm.py", line 1078, in _get_address_from_loadbalancer
2024-12-17T11:46:58.668Z [container-agent]     if len(ingresses) != 1:
2024-12-17T11:46:58.668Z [container-agent] TypeError: object of type 'NoneType' has no len()
2024-12-17T11:46:59.003Z [container-agent] 2024-12-17 11:46:59 ERROR juju.worker.uniter.operation runhook.go:180 hook "istio-pilot-relation-created" (via hook dispatching script: dispatch) failed: exit status 1
2024-12-17T11:46:59.005Z [container-agent] 2024-12-17 11:46:59 INFO juju.worker.uniter resolver.go:180 awaiting error resolution for "relation-created" hook
2024-12-17T11:47:00.302Z [pebble] Check "readiness" failure 53 (threshold 3): received non-20x status code 418
2024-12-17T11:47:10.303Z [pebble] Check "readiness" failure 54 (threshold 3): received non-20x status code 418
2024-12-17T11:47:20.303Z [pebble] Check "readiness" failure 55 (threshold 3): received non-20x status code 418
```

### Additional Context

![image](https://github.com/user-attachments/assets/99ee6720-1a04-486d-a9f8-4bc17a429591)

**Comment by misohu** [comment]
Hi can you make sure Loadbalancer type of service is enabled in your cluster?
