### ISSUE TITLE
kubeflow-lite bundle hook failed: "install" on jupyter-controller/0

### ISSUE THREAD

**Issue by davecore82** [canonical/bundle-kubeflow#335]
I'm deploying cs:~kubeflow-charmers/bundle/kubeflow-lite-53 inside a k8s model with Juju 2.8.9 and I get the following juju status:

```
Model      Controller             Cloud/Region          Version  SLA          Timestamp
kubeflow2  maas_cloud_controller  kubeflow-k8s/default  2.8.9    unsupported  20:16:02Z

App                          Version                         Status   Scale  Charm                        Store       Rev  OS          Address         Notes
admission-webhook            registry.jujucharms.com/kub...  active       1  admission-webhook            jujucharms    8  kubernetes  10.152.183.85   
argo-controller              registry.jujucharms.com/kub...  active       1  argo-controller              jujucharms   46  kubernetes    
dex-auth                     registry.jujucharms.com/kub...  active       1  dex-auth                     jujucharms   45  kubernetes  10.152.183.201  
istio-ingressgateway                                         blocked      1  istio-ingressgateway         jujucharms    8  kubernetes                  istio-ca-root-cert certificate not found.
istio-pilot                  registry.jujucharms.com/ist...  active       1  istio-pilot                  jujucharms    8  kubernetes  10.152.183.186  
jupyter-controller                                           error        1  jupyter-controller           jujucharms   46  kubernetes                  hook failed: "install"
jupyter-web                  registry.jujucharms.com/kub...  active       1  jupyter-web                  jujucharms   47  kubernetes  10.152.183.104  
kubeflow-dashboard           registry.jujucharms.com/kub...  active       1  kubeflow-dashboard           jujucharms   46  kubernetes  10.152.183.217  
kubeflow-profiles            registry.jujucharms.com/kub...  active       1  kubeflow-profiles            jujucharms   44  kubernetes  10.152.183.211  
minio                        registry.jujucharms.com/kub...  active       1  minio                        jujucharms   45  kubernetes  10.152.183.46   
oidc-gatekeeper              registry.jujucharms.com/kub...  active       1  oidc-gatekeeper              jujucharms   45  kubernetes  10.152.183.58   
pipelines-api                registry.jujucharms.com/kub...  active       1  pipelines-api                jujucharms   47  kubernetes  10.152.183.171  
pipelines-db                 rocks.canonical.com:443/mar...  active       1  mariadb-k8s                  jujucharms   35  kubernetes  10.152.183.243  
pipelines-persistence        registry.jujucharms.com/kub...  active       1  pipelines-persistence        jujucharms   46  kubernetes    
pipelines-scheduledworkflow  registry.jujucharms.com/kub...  active       1  pipelines-scheduledworkflow  jujucharms   46  kubernetes                      
pipelines-ui                 registry.jujucharms.com/kub...  active       1  pipelines-ui                 jujucharms   48  kubernetes  10.152.183.57   
pipelines-viewer             registry.jujucharms.com/kub...  active       1  pipelines-viewer             jujucharms   45  kubernetes                      
pipelines-visualization      registry.jujucharms.com/kub...  active       1  pipelines-visualization      jujucharms   45  kubernetes  10.152.183.159  
pytorch-operator             registry.jujucharms.com/kub...  active       1  pytorch-operator             jujucharms   47  kubernetes                      
seldon-core                  registry.jujucharms.com/kub...  active       1  seldon-core                  jujucharms   48  kubernetes  10.152.183.83   
tf-job-operator              registry.jujucharms.com/kub...  active       1  tf-job-operator              jujucharms   44  kubernetes    

Unit                            Workload  Agent  Address     Ports                                   Message
admission-webhook/0*            active    idle   10.1.24.44  443/TCP        
argo-controller/0*              active    idle   10.1.17.46        
dex-auth/0*                     active    idle   10.1.14.63  5556/TCP        
istio-ingressgateway/0*         blocked   idle                                                       istio-ca-root-cert certificate not found.
istio-pilot/0*                  active    idle   10.1.17.43  8080/TCP,15010/TCP,15012/TCP,15017/TCP  
jupyter-controller/0*           error     idle                                                       hook failed: "install"
jupyter-web/0*                  active    idle   10.1.24.48  5000/TCP        
kubeflow-dashboard/0*           active    idle   10.1.17.47  8082/TCP        
kubeflow-profiles/0*            active    idle   10.1.14.66  8080/TCP,8081/TCP        
minio/0*                        active    idle   10.1.17.48  9000/TCP        
oidc-gatekeeper/0*              active    idle   10.1.24.50  8080/TCP        
pipelines-api/0*                active    idle   10.1.82.25  8887/TCP,8888/TCP,15090/TCP        
pipelines-db/0*                 active    idle   10.1.24.53  3306/TCP                                ready
pipelines-persistence/0*        active    idle   10.1.14.67        
pipelines-scheduledworkflow/0*  active    idle   10.1.24.52                                                  
pipelines-ui/0*                 active    idle   10.1.17.52  3000/TCP        
pipelines-viewer/0*             active    idle   10.1.17.51                                               
pipelines-visualization/0*      active    idle   10.1.24.55  8888/TCP        
pytorch-operator/0*             active    idle   10.1.14.71        
seldon-core/0*                  active    idle   10.1.17.53  8080/TCP,9876/TCP       
tf-job-operator/0*              active    idle   10.1.24.56       
```

I did not investigate the blocked istio-ingressgateway/0 yet but the jupyter-controller/0 has this in the juju debug-log:

```
[...]
application-jupyter-controller: 20:14:11 INFO juju.worker.caasoperator.uniter.jupyter-controller/0 awaiting error resolution for "install" hook
application-jupyter-controller: 20:14:12 INFO unit.jupyter-controller/0.juju-log Reactive main running for hook install
application-jupyter-controller: 20:14:12 INFO unit.jupyter-controller/0.juju-log Invoking reactive handler: reactive/jupyter_controller.py:21:update_image
application-jupyter-controller: 20:14:12 INFO unit.jupyter-controller/0.juju-log Invoking reactive handler: reactive/docker_resource.py:7:auto_fetch
application-jupyter-controller: 20:14:12 INFO unit.jupyter-controller/0.juju-log Invoking reactive handler: reactive/docker_resource.py:18:fetch
application-jupyter-controller: 20:14:12 INFO unit.jupyter-controller/0.juju-log status-set: maintenance: fetching resource: oci-image
application-jupyter-controller: 20:14:13 INFO unit.jupyter-controller/0.juju-log Invoking reactive handler: reactive/jupyter_controller.py:31:start_charm
application-jupyter-controller: 20:14:13 INFO unit.jupyter-controller/0.juju-log status-set: maintenance: configuring container
application-jupyter-controller: 20:14:13 ERROR unit.jupyter-controller/0.juju-log pod-spec-set encountered an error: `ERROR rules is required`
application-jupyter-controller: 20:14:13 ERROR unit.jupyter-controller/0.juju-log Hook error:
Traceback (most recent call last):
  File "lib/charms/reactive/__init__.py", line 74, in main
    bus.dispatch(restricted=restricted_mode)
  File "lib/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "lib/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "lib/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-jupyter-controller-0/charm/reactive/jupyter_controller.py", line 44, in start_charm
    layer.caas_base.pod_spec_set(
  File "lib/charms/layer/caas_base.py", line 34, in pod_spec_set
    run_hook_command("pod-spec-set", spec)
  File "lib/charms/layer/caas_base.py", line 13, in run_hook_command
    run([cmd], stdout=PIPE, stderr=PIPE, check=True, input=stdin.encode('utf-8'))
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pod-spec-set']' returned non-zero exit status 1.

application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install Traceback (most recent call last):
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install   File "/var/lib/juju/agents/unit-jupyter-controller-0/charm/hooks/install", line 19, in <module>
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install     main()
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install   File "lib/charms/reactive/__init__.py", line 74, in main
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install     bus.dispatch(restricted=restricted_mode)
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install   File "lib/charms/reactive/bus.py", line 390, in dispatch
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install     _invoke(other_handlers)
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install   File "lib/charms/reactive/bus.py", line 359, in _invoke
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install     handler.invoke()
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install   File "lib/charms/reactive/bus.py", line 181, in invoke
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install     self._action(*args)
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install   File "/var/lib/juju/agents/unit-jupyter-controller-0/charm/reactive/jupyter_controller.py", line 44, in start_charm
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install     layer.caas_base.pod_spec_set(
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install   File "lib/charms/layer/caas_base.py", line 34, in pod_spec_set
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install     run_hook_command("pod-spec-set", spec)
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install   File "lib/charms/layer/caas_base.py", line 13, in run_hook_command
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install     run([cmd], stdout=PIPE, stderr=PIPE, check=True, input=stdin.encode('utf-8'))
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install   File "/usr/lib/python3.8/subprocess.py", line 512, in run
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install     raise CalledProcessError(retcode, process.args,
application-jupyter-controller: 20:14:13 WARNING unit.jupyter-controller/0.install subprocess.CalledProcessError: Command '['pod-spec-set']' returned non-zero exit status 1.
application-jupyter-controller: 20:14:13 ERROR juju.worker.caasoperator.uniter.jupyter-controller/0.operation hook "install" (via explicit, bespoke hook script) failed: exit status 1
application-jupyter-controller: 20:14:13 INFO juju.worker.caasoperator.uniter.jupyter-controller/0 awaiting error resolution for "install" hook
```

**Comment by knkski** [comment]
I can reproduce this, but not quite sure what's going on, since `rules` is defined:

https://api.jujucharms.com/charmstore/v5/jupyter-controller-46/archive/reactive/jupyter_controller.py

**Comment by knkski** [comment]
It looks like this was caused by accidentally pushing a version of this split-off Jupyter bundle into the charm store before it was stable: https://github.com/canonical/bundle-jupyter/

Until the bundle can be updated with the correct version, the easiest way to deploy the kubeflow lite bundle is to deploy `cs:kubeflow-lite-37`

**Comment by DomFleischmann** [comment]
With the latest bundle being relased this issue can be closed.
