### ISSUE TITLE
Error while installing Kubeflow dashboard 

### ISSUE THREAD

**Issue by pshegde** [canonical/bundle-kubeflow#407]
Hi,

While trying to install kubeflow using charmed operators on a custom k8s cluster the kubeflow-dashboard install fails with this error - hook "ingress-relation-changed". Is there any workaround available to fix this?

juju debug-log gives me this - 

application-kubeflow-dashboard: 14:26:06 ERROR unit.kubeflow-dashboard/2.juju-log ingress:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kubeflow-dashboard-2/charm/venv/serialized_data_interface/__init__.py", line 132, in send_data
    validate(instance=data, schema=self.schema[self.versions[rel.app.name]])
KeyError: 'v1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 183, in <module>
    main(Operator)
  File "/var/lib/juju/agents/unit-kubeflow-dashboard-2/charm/venv/ops/main.py", line 402, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-kubeflow-dashboard-2/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-kubeflow-dashboard-2/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-kubeflow-dashboard-2/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-kubeflow-dashboard-2/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 56, in configure_mesh
    self.interfaces["ingress"].send_data(
  File "/var/lib/juju/agents/unit-kubeflow-dashboard-2/charm/venv/serialized_data_interface/__init__.py", line 134, in send_data
    raise NoSchemaDefined(self.end)
serialized_data_interface.NoSchemaDefined: Calling send_data from the requires end of a relation requires defining a requires section in the schema.
application-kubeflow-dashboard: 14:26:06 ERROR juju.worker.caasoperator.uniter.kubeflow-dashboard/2.operation hook "ingress-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
application-kubeflow-dashboard: 14:26:06 INFO juju.worker.caasoperator.uniter.kubeflow-dashboard/2 awaiting error resolution for "relation-changed" hook

**Comment by DomFleischmann** [comment]
Hello @pshegde what kind of bundle did you use to deploy kubeflow?

**Comment by pshegde** [comment]
The bundle used is juju cs:kubeflow 1.3. Retried using kubernetes version 1.20 and I dont see this error anymore.
