### ISSUE TITLE
Failed to launch Katib experiment

### ISSUE THREAD

**Issue by pshegde** [canonical/bundle-kubeflow#415]
Hi,

I see this issue on Kubeflow 1.3. More details here - https://github.com/kubeflow/katib/issues/1455. 
Has anyone seen this error before? Any pointers on how to fix this?

2021-12-03 23:15:24 run:120 [ERROR] [TID=kl824ee10y] [/home/jovyan/kale/examples/dog-breed-classification/dog-breed-katib.ipynb] RPC function 'create_katib_experiment' raised an RPCError
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/katib.py", line 104, in _launch_katib_experiment
    katib_experiment)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 178, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 277, in create_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 377, in request
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'ab77065d-ed04-4fa5-bd00-a66298a0e074', 'X-Kubernetes-Pf-Prioritylevel-Uid': '55506d34-196f-4b07-b92d-80a43a2898e6', 'Date': 'Fri, 03 Dec 2021 23:15:24 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found

**Comment by DomFleischmann** [comment]
This should be fixed with our latest Charmed Kubeflow release, please reopen if it still applies.
