### ISSUE TITLE
Deployment using Quickstart https://charmed-kubeflow.io/docs/quickstart

### ISSUE THREAD

**Issue by Barteus** [canonical/bundle-kubeflow#494]
When following the Quickstart guide to install the Charmed Kubeflow the result is green juju status and all pods are created correctly, but there is no gateway. When the gateway is created manually then it works fine.

Workaround by @misohu (thanks!):
```
cat <<EOF | kubectl create -f -
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
 creationTimestamp: "2022-09-12T15:40:34Z"
 generation: 1
 labels:
   app.istio-pilot.io/is-workload-entity: "true"
   app.juju.is/created-by: istio-pilot
 name: kubeflow-gateway
 namespace: kubeflow
 resourceVersion: "2203"
 selfLink: /apis/networking.istio.io/v1beta1/namespaces/kubeflow/gateways/kubeflow-gateway
 uid: 931fe3b7-08a8-42a0-b366-96b6473739c3
spec:
 selector:
   istio: ingressgateway
 servers:
 - hosts:
   - '*'
   port:
     name: http
     number: 80
     protocol: HTTP
EOF
```

**Comment by ca-scribner** [comment]
This feels like what canonical/istio-operators#94 raised and canonical/istio-operators#102 tried to fix.  Maybe it still is a problem?

**Comment by VariableDeclared** [comment]
Can confrim I hit this issue today; debug-log
```
unit-istio-pilot-0: 14:56:32 ERROR unit.istio-pilot/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 333, in <module>
    main(Operator)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 424, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 746, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 783, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 72, in install
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./istioctl', 'install', '-y', '-s', 'profile=minimal', '-s', 'values.global.istioNamespace=kubeflow']' returned non-zero exit status 1.
```

**Comment by DnPlas** [comment]
This issue is identified and tracked [here](https://github.com/canonical/istio-operators/issues/113). Although the workaround provided by @misohu is fine, I suggest you follow the workaround in the linked Github issue. Closing this as it is tracked in isto's repository.
