### ISSUE TITLE
URLs for pipelines are broken

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/bundle-kubeflow#607]
these URLs lead to 404

https://github.com/canonical/bundle-kubeflow/blob/0b06bf138c77e74d77d71beef02dcdc4ba0c473a/tests/pipelines/mnist.py#L291-L294

traceback from pipelines:
```
Downloading data from https://github.com/canonical/bundle-kubeflow/raw/test-artifacts/tests/pipelines/artifacts/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 251, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/tmp.mzd3tUZApA", line 81, in <module>
    _outputs = load_task(**_parsed_args)
  File "/tmp/tmp.mzd3tUZApA", line 46, in load_task
    train_x = parse_images(load(train_images))
  File "/tmp/tmp.mzd3tUZApA", line 29, in load
    return GzipFile(get_file(Path(path).name, path)).read()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 253, in get_file
    raise Exception(error_msg.format(origin, e.code, e.msg))
Exception: URL fetch failure on https://github.com/canonical/bundle-kubeflow/raw/test-artifacts/tests/pipelines/artifacts/train-images-idx3-ubyte.gz: 404 -- Not Found
```

**Comment by orfeas-k** [comment]
(adding some more context for future reference although we closed this)

**Steps to reproduce**
1. Go to revision 84 of the [Getting started with Kubeflow](https://discourse.charmhub.io/t/get-started-with-charmed-kubeflow/7819) guide
2. Follow the steps from `Kubeflow Pipelines` part of the guide in a Kubeflow deployment.

**Comment by ColmBhandal** [comment]
> (adding some more context for future reference although we closed this)
> 
> **Steps to reproduce**
> 
> 1. Go to revision 84 of the [Getting started with Kubeflow](https://discourse.charmhub.io/t/get-started-with-charmed-kubeflow/7819) guide
> 2. Follow the steps from `Kubeflow Pipelines` part of the guide in a Kubeflow deployment.

FYI that part of the doc is migrated to here: https://discourse.charmhub.io/t/explore-kubeflow/10974.

Also note the section is officially commented out until this is fixed

**Comment by kimwnasptd** [comment]
Commenting here in case people bump into this. In order to avoid the 404 errors you can run the following commands to update the problematic `mnist.py`

```bash
cd tests/pipelines/

sed -i 's#https://github.com/canonical/bundle-kubeflow/raw/test-artifacts/tests/pipelines/artifacts/train-images-idx3-ubyte.gz#https://huggingface.co/spaces/chrisjay/mnist-adversarial/resolve/603879aac618aca69749a8a9172daec23a9dd2c4/files/MNIST/raw/train-images-idx3-ubyte.gz#g' mnist.py
sed -i 's#https://github.com/canonical/bundle-kubeflow/raw/test-artifacts/tests/pipelines/artifacts/train-labels-idx1-ubyte.gz#https://huggingface.co/spaces/chrisjay/mnist-adversarial/resolve/603879aac618aca69749a8a9172daec23a9dd2c4/files/MNIST/raw/train-labels-idx1-ubyte.gz#g' mnist.py
sed -i 's#https://github.com/canonical/bundle-kubeflow/raw/test-artifacts/tests/pipelines/artifacts/t10k-images-idx3-ubyte.gz#https://huggingface.co/spaces/chrisjay/mnist-adversarial/resolve/603879aac618aca69749a8a9172daec23a9dd2c4/files/MNIST/raw/t10k-images-idx3-ubyte.gz#g' mnist.py
sed -i 's#https://github.com/canonical/bundle-kubeflow/raw/test-artifacts/tests/pipelines/artifacts/t10k-labels-idx1-ubyte.gz#https://huggingface.co/spaces/chrisjay/mnist-adversarial/resolve/603879aac618aca69749a8a9172daec23a9dd2c4/files/MNIST/raw/t10k-labels-idx1-ubyte.gz#g' mnist.py
```
