### ISSUE TITLE
Kubeflow is not published for arm64

### ISSUE THREAD

**Issue by Basdbruijne** [canonical/bundle-kubeflow#656]
With SQA, we were trying to deploy ckf 1.7 on an arm64 machine:

```
2023-08-08-10:40:46 root DEBUG [localhost]: juju deploy -m foundations-kubernetes:kubeflow --debug --channel=1.7/stable --overlay ./config/kubeflow_options.yaml --trust ch:kubeflow
2023-08-08-10:40:46 root DEBUG 10:40:46 INFO  juju.cmd supercommand.go:56 running juju [3.2.2 bbad9d12de0ebefbd33af942599cc7760c59a1a3 gc go1.20.6]
2023-08-08-10:40:46 root DEBUG 10:40:46 DEBUG juju.cmd supercommand.go:57   args: []string{"/snap/juju/23846/bin/juju", "deploy", "-m", "foundations-kubernetes:kubeflow", "--debug", "--channel=1.7/stable", "--overlay", "./config/kubeflow_options.yaml", "--trust", "ch:kubeflow"}
2023-08-08-10:40:46 root DEBUG 10:40:46 INFO  juju.juju api.go:86 connecting to API addresses: [10.152.183.46:17070]
2023-08-08-10:40:46 root DEBUG 10:40:46 DEBUG juju.api apiclient.go:639 starting proxier for connection
2023-08-08-10:40:46 root DEBUG 10:40:46 DEBUG juju.api apiclient.go:643 tunnel proxy in use at localhost on port 33165
2023-08-08-10:40:46 root DEBUG 10:40:46 DEBUG juju.api apiclient.go:1166 successfully dialed "wss://localhost:33165/model/9250114a-82f8-486b-8a08-de414dabbfab/api"
2023-08-08-10:40:46 root DEBUG 10:40:46 INFO  juju.api apiclient.go:1068 cannot resolve "localhost": lookup localhost: operation was canceled
2023-08-08-10:40:46 root DEBUG 10:40:46 INFO  juju.api apiclient.go:701 connection established to "wss://localhost:33165/model/9250114a-82f8-486b-8a08-de414dabbfab/api"
2023-08-08-10:40:46 root DEBUG 10:40:46 INFO  juju.juju api.go:86 connecting to API addresses: [10.152.183.46:17070]
2023-08-08-10:40:47 root DEBUG 10:40:47 DEBUG juju.api apiclient.go:639 starting proxier for connection
2023-08-08-10:40:47 root DEBUG 10:40:47 DEBUG juju.api apiclient.go:643 tunnel proxy in use at localhost on port 44021
2023-08-08-10:40:47 root DEBUG 10:40:47 DEBUG juju.api apiclient.go:819 looked up localhost -> [127.0.0.1]
2023-08-08-10:40:47 root DEBUG 10:40:47 DEBUG juju.api apiclient.go:1166 successfully dialed "wss://localhost:44021/api"
2023-08-08-10:40:47 root DEBUG 10:40:47 INFO  juju.api apiclient.go:701 connection established to "wss://localhost:44021/api"
2023-08-08-10:40:48 root DEBUG 10:40:48 INFO  cmd bundle.go:351 Located bundle "kubeflow" in charm-hub, revision 340
2023-08-08-10:40:48 root DEBUG 10:40:48 DEBUG juju.cmd.juju.application.deployer bundlehandler.go:259 model: &bundlechanges.Model{
2023-08-08-10:40:48 root DEBUG     Applications: {
2023-08-08-10:40:48 root DEBUG     },
2023-08-08-10:40:48 root DEBUG     Machines: {
2023-08-08-10:40:48 root DEBUG     },
2023-08-08-10:40:48 root DEBUG     Relations:        nil,
2023-08-08-10:40:48 root DEBUG     ConstraintsEqual: func(string, string) bool {...},
2023-08-08-10:40:48 root DEBUG     Sequence:         {},
2023-08-08-10:40:48 root DEBUG     sequence:         {},
2023-08-08-10:40:48 root DEBUG     MachineMap:       {},
2023-08-08-10:40:48 root DEBUG     logger:           nil,
2023-08-08-10:40:48 root DEBUG }
2023-08-08-10:40:48 root DEBUG 10:40:48 DEBUG juju.api monitor.go:35 RPC connection died
2023-08-08-10:40:48 root DEBUG 10:40:48 DEBUG juju.api monitor.go:35 RPC connection died
2023-08-08-10:40:48 root DEBUG ERROR cannot deploy bundle: cannot resolve charm or bundle "admission-webhook": selecting releases: charm or bundle not found for channel "1.7/stable", platform "arm64"
2023-08-08-10:40:48 root DEBUG 10:40:48 DEBUG cmd supercommand.go:548 error stack: 
2023-08-08-10:40:48 root DEBUG selecting releases: charm or bundle not found for channel "1.7/stable", platform "arm64"
2023-08-08-10:40:48 root DEBUG github.com/juju/juju/cmd/juju/application/store.(*CharmAdaptor).ResolveCharm:75: 
2023-08-08-10:40:48 root DEBUG github.com/juju/juju/cmd/juju/application/deployer.(*bundleHandler).resolveCharmsAndEndpoints:355: cannot resolve charm or bundle "admission-webhook"
2023-08-08-10:40:48 root DEBUG github.com/juju/juju/cmd/juju/application/deployer.bundleDeploy:94: 
2023-08-08-10:40:48 root DEBUG github.com/juju/juju/cmd/juju/application/deployer.(*deployBundle).deploy:176: cannot deploy bundle
2023-08-08-10:40:48 root ERROR [localhost] Command failed: juju deploy -m foundations-kubernetes:kubeflow --debug --channel=1.7/stable --overlay ./config/kubeflow_options.yaml --trust ch:kubeflow
2023-08-08-10:40:48 root ERROR 1[localhost] STDOUT follows:

2023-08-08-10:40:48 root ERROR 2[localhost] STDERR follows:
10:40:46 INFO  juju.cmd supercommand.go:56 running juju [3.2.2 bbad9d12de0ebefbd33af942599cc7760c59a1a3 gc go1.20.6]
10:40:46 DEBUG juju.cmd supercommand.go:57   args: []string{"/snap/juju/23846/bin/juju", "deploy", "-m", "foundations-kubernetes:kubeflow", "--debug", "--channel=1.7/stable", "--overlay", "./config/kubeflow_options.yaml", "--trust", "ch:kubeflow"}
10:40:46 INFO  juju.juju api.go:86 connecting to API addresses: [10.152.183.46:17070]
10:40:46 DEBUG juju.api apiclient.go:639 starting proxier for connection
10:40:46 DEBUG juju.api apiclient.go:643 tunnel proxy in use at localhost on port 33165
10:40:46 DEBUG juju.api apiclient.go:1166 successfully dialed "wss://localhost:33165/model/9250114a-82f8-486b-8a08-de414dabbfab/api"
10:40:46 INFO  juju.api apiclient.go:1068 cannot resolve "localhost": lookup localhost: operation was canceled
10:40:46 INFO  juju.api apiclient.go:701 connection established to "wss://localhost:33165/model/9250114a-82f8-486b-8a08-de414dabbfab/api"
10:40:46 INFO  juju.juju api.go:86 connecting to API addresses: [10.152.183.46:17070]
10:40:47 DEBUG juju.api apiclient.go:639 starting proxier for connection
10:40:47 DEBUG juju.api apiclient.go:643 tunnel proxy in use at localhost on port 44021
10:40:47 DEBUG juju.api apiclient.go:819 looked up localhost -> [127.0.0.1]
10:40:47 DEBUG juju.api apiclient.go:1166 successfully dialed "wss://localhost:44021/api"
10:40:47 INFO  juju.api apiclient.go:701 connection established to "wss://localhost:44021/api"
10:40:48 INFO  cmd bundle.go:351 Located bundle "kubeflow" in charm-hub, revision 340
10:40:48 DEBUG juju.cmd.juju.application.deployer bundlehandler.go:259 model: &bundlechanges.Model{
    Applications: {
    },
    Machines: {
    },
    Relations:        nil,
    ConstraintsEqual: func(string, string) bool {...},
    Sequence:         {},
    sequence:         {},
    MachineMap:       {},
    logger:           nil,
}
10:40:48 DEBUG juju.api monitor.go:35 RPC connection died
10:40:48 DEBUG juju.api monitor.go:35 RPC connection died
ERROR cannot deploy bundle: cannot resolve charm or bundle "admission-webhook": selecting releases: charm or bundle not found for channel "1.7/stable", platform "arm64"
10:40:48 DEBUG cmd supercommand.go:548 error stack: 
selecting releases: charm or bundle not found for channel "1.7/stable", platform "arm64"
github.com/juju/juju/cmd/juju/application/store.(*CharmAdaptor).ResolveCharm:75: 
github.com/juju/juju/cmd/juju/application/deployer.(*bundleHandler).resolveCharmsAndEndpoints:355: cannot resolve charm or bundle "admission-webhook"
github.com/juju/juju/cmd/juju/application/deployer.bundleDeploy:94: 
github.com/juju/juju/cmd/juju/application/deployer.(*deployBundle).deploy:176: cannot deploy bundle

Traceback (most recent call last):
  File "/usr/local/bin/fce", line 33, in <module>
    sys.exit(load_entry_point('foundationcloudengine', 'console_scripts', 'fce')())
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/main.py", line 217, in entry_point
    sys.exit(main(sys.argv[1:]))
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/main.py", line 208, in main
    opts.func(opts)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/command.py", line 94, in run
    self.run_per_layer(layer, args)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/commands/build.py", line 46, in run_per_layer
    build_and_validate_if_needed(
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/commands/build.py", line 98, in build_and_validate_if_needed
    layer.build_outer(only_steps)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/baselayer.py", line 160, in build_outer
    self.build(only_steps=only_steps)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/jujuworkloadlayer.py", line 1412, in build
    self.run_steps(only_steps)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/steppedbaselayer.py", line 110, in run_steps
    step.build()
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/jujuworkloadlayer.py", line 1004, in build
    deploy(
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/juju_cli.py", line 191, in deploy
    local(command, output_mode="live")
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/remotehelpers.py", line 278, in local
    return run_cmd(cmd, target_machine, **kwargs)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/remotehelpers.py", line 209, in run_cmd
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['juju', 'deploy', '-m', 'foundations-kubernetes:kubeflow', '--debug', '--channel=1.7/stable', '--overlay', './config/kubeflow_options.yaml', '--trust', 'ch:kubeflow']' returned non-zero exit status 1.
Build step 'Execute shell' marked build as failure
```

Are there plans for supporting arm64? Would it make sense for SQA to step testing ckf on ARM64 for now?

**Comment by orfeas-k** [comment]
Thank you the question @Basdbruijne. Currently, we do not support CKF on `arm64` architectures. There are going to be efforts towards this direction, but until we confirm that we fully support it, it doesn't make sense to test that on ARM64. Closing this issue but feel free to re-open it if you have any more questions.
