### ISSUE TITLE
Installation error of kubeflow 1.8

### ISSUE THREAD

**Issue by C-Jaewon** [canonical/bundle-kubeflow#759]
### Bug Description

![스크린샷 2023-11-27 11-39-27](https://github.com/canonical/bundle-kubeflow/assets/20211880/06bd78b8-a7b0-47d0-8667-cb63456ff835)

### To Reproduce

sudo snap install microk8s --classic --channel=1.26/stable
sudo usermod -a -G microk8s $USER
newgrp microk8s
sudo chown -f -R $USER ~/.kube
IPADDR=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')
microk8s enable dns ingress metallb:$IPADDR-$IPADDR

microk8s enable helm3
microk8s helm3 repo add csi-driver-nfs https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
microk8s helm3 repo update

microk8s helm3 install csi-driver-nfs csi-driver-nfs/csi-driver-nfs \
    --namespace kube-system \
    --set kubeletDir=/var/snap/microk8s/common/var/lib/kubelet
microk8s kubectl get csidrivers

mount.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
#provisioner: microk8s.io/hostpath
parameters:
  server: 192.168.0.97
  share: /volume1/USER_SHARE/datasets/default-storage
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - defaults

kubectl apply -f mount.yaml
kubectl patch storageclass nfs-csi -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
sudo snap install juju --classic --channel=3.1/stable
mkdir -p ~/.local/share

microk8s config | juju add-k8s my-k8s --client --storage=nfs-csi
juju bootstrap my-k8s uk8sx
juju add-model kubeflow
sudo sysctl fs.inotify.max_user_instances=1280
sudo sysctl fs.inotify.max_user_watches=655360
juju deploy kubeflow --trust  --channel=1.8/stable

### Environment

I am using the version of Ubuntu 22.04 Desktop installed on my local pc.

### Relevant Log Output

```shell
2023-11-24T11:17:50.145Z [container-agent] During handling of the above exception, another exception occurred:
2023-11-24T11:17:50.145Z [container-agent] 
2023-11-24T11:17:50.145Z [container-agent] Traceback (most recent call last):
2023-11-24T11:17:50.145Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-db-0/charm/./src/charm.py", line 724, in <module>
2023-11-24T11:17:50.145Z [container-agent]     main(MySQLOperatorCharm)
2023-11-24T11:17:50.145Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-db-0/charm/venv/ops/main.py", line 441, in main
2023-11-24T11:17:50.145Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)
2023-11-24T11:17:50.145Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-db-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
2023-11-24T11:17:50.145Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2023-11-24T11:17:50.145Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-db-0/charm/venv/ops/framework.py", line 344, in emit
2023-11-24T11:17:50.145Z [container-agent]     framework._emit(event)
2023-11-24T11:17:50.145Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-db-0/charm/venv/ops/framework.py", line 841, in _emit
2023-11-24T11:17:50.145Z [container-agent]     self._reemit(event_path)
2023-11-24T11:17:50.145Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-db-0/charm/venv/ops/framework.py", line 930, in _reemit
2023-11-24T11:17:50.145Z [container-agent]     custom_handler(event)
2023-11-24T11:17:50.145Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-db-0/charm/./src/charm.py", line 545, in _on_mysql_pebble_ready
2023-11-24T11:17:50.145Z [container-agent]     self._mysql.create_cluster(self.unit_label)
2023-11-24T11:17:50.145Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-db-0/charm/lib/charms/mysql/v0/mysql.py", line 1102, in create_cluster
2023-11-24T11:17:50.145Z [container-agent]     raise MySQLCreateClusterError(e.message)
2023-11-24T11:17:50.145Z [container-agent] charms.mysql.v0.mysql.MySQLCreateClusterError: Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Loading startup files...
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Loading plugins...
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Connecting to MySQL at: serverconfig@kfp-db-0.kfp-db-endpoints
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Shell.connect: tid=9: CONNECTED: kfp-db-0.kfp-db-endpoints
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Connecting to MySQL at: mysql://serverconfig@kfp-db-0.kfp-db-endpoints:3306?connect-timeout=5000
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Dba.create_cluster: tid=10: CONNECTED: kfp-db-0.kfp-db-endpoints:3306
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Connecting to MySQL at: mysql://serverconfig@kfp-db-0.kfp-db-endpoints:3306?connect-timeout=5000
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Dba.create_cluster: tid=11: CONNECTED: kfp-db-0.kfp-db-endpoints:3306
2023-11-24T11:17:50.145Z [container-agent] A new InnoDB Cluster will be created on instance 'kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306'.
2023-11-24T11:17:50.145Z [container-agent] 
2023-11-24T11:17:50.145Z [container-agent] Validating instance configuration at kfp-db-0.kfp-db-endpoints:3306...
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Connecting to MySQL at: mysql://serverconfig@kfp-db-0.kfp-db-endpoints:3306?connect-timeout=5000
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Dba.create_cluster: tid=12: CONNECTED: kfp-db-0.kfp-db-endpoints:3306
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Validating account serverconfig@%...
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: serverconfig user has 1 accounts with wildcard or netmask and 0 without
2023-11-24T11:17:50.145Z [container-agent] 
2023-11-24T11:17:50.145Z [container-agent] This instance reports its own address as kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Validating InnoDB page size of instance 'kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306'.
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Checking if performance_schema is enabled on instance 'kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306'.
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Validating configuration of kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306 (mycnf = )
2023-11-24T11:17:50.145Z [container-agent] 
2023-11-24T11:17:50.145Z [container-agent] Instance configuration is suitable.
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: SSL mode used to configure the cluster: 'REQUIRED'
2023-11-24T11:17:50.145Z [container-agent] NOTE: Group Replication will communicate with other members using 'kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306'. Use the localAddress option to override.
2023-11-24T11:17:50.145Z [container-agent] 
2023-11-24T11:17:50.145Z [container-agent] * Checking connectivity and SSL configuration...
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Checking connection from kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306 to mysqlsh.test@kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306 (report_host) ssl_mode=REQUIRED auth_type=PASSWORD cert_issuer= cert_subject=
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Setting up async source for channel 'mysqlsh.test' of kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306 to kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306 (user 'mysqlsh.test')
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Connection check kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306 -> kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306 io_state=OFF io_error=Fatal error: The replica I/O thread stops because source and replica have equal MySQL server ids; these ids must be different for replication to work (or the --replicate-same-server-id option must be used on replica but this does not always make sense; please check the manual before using it). (13117) at 2023-11-24 11:17:48.645352
2023-11-24T11:17:50.145Z [container-agent] 
2023-11-24T11:17:50.145Z [container-agent] Creating InnoDB Cluster 'cluster-e51f82aa7814f1380f94e511474b2acf' on 'kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306'...
2023-11-24T11:17:50.145Z [container-agent] 
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Using Group Replication single primary mode: TRUE
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Using Group Replication SSL mode: REQUIRED
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Using Group Replication group name: 199d6c30-8abb-11ee-9ae6-52caba1629a1
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Using Group Replication local address: kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Using Group Replication Communication Stack: MYSQL
2023-11-24T11:17:50.145Z [container-agent] Adding Seed Instance...
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Creating recovery account 'mysql_innodb_cluster_959145607'@'%' for instance 'kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306'
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:48Z: Dba.create_cluster: tid=10: MySQL Error 1141 (42000): There is no such grant defined for user 'mysql_innodb_cluster_959145607' on host '%', SQL: SHOW GRANTS FOR 'mysql_innodb_cluster_959145607'@'%'
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:49Z: Dba.create_cluster: tid=10: MySQL Error 3096 (HY000): The START GROUP_REPLICATION command failed as there was an error when initializing the group communication layer., SQL: START GROUP_REPLICATION
2023-11-24T11:17:50.145Z [container-agent] ERROR: Unable to start Group Replication for instance 'kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306'.
2023-11-24T11:17:50.145Z [container-agent] The MySQL error_log contains the following messages:
2023-11-24T11:17:50.145Z [container-agent]   2023-11-24 11:17:48.988478 [System] [MY-013587] Plugin group_replication reported: 'Plugin 'group_replication' is starting.'
2023-11-24T11:17:50.145Z [container-agent]   2023-11-24 11:17:48.989260 [Error] [MY-011735] Plugin group_replication reported: '[GCS] Error in associated permissions to path '/var/lib/mysql/'.'
2023-11-24T11:17:50.145Z [container-agent]   2023-11-24 11:17:48.989315 [Error] [MY-011674] Plugin group_replication reported: 'Unable to initialize the group communication engine'
2023-11-24T11:17:50.145Z [container-agent]   2023-11-24 11:17:48.989335 [Error] [MY-011637] Plugin group_replication reported: 'Error on group communication engine initialization'
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:49Z: createCluster() failed: Trying to revert changes...
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:49Z: revert: Stopping group_replication
2023-11-24T11:17:50.145Z [container-agent] verbose: 2023-11-24T11:17:49Z: revert: Clearing super_read_only
2023-11-24T11:17:50.145Z [container-agent] Traceback (most recent call last):
2023-11-24T11:17:50.145Z [container-agent]   File "<string>", line 2, in <module>
2023-11-24T11:17:50.145Z [container-agent] RuntimeError: Dba.create_cluster: Group Replication failed to start: MySQL Error 3096 (HY000): kfp-db-0.kfp-db-endpoints.kubeflow.svc.cluster.local:3306: The START GROUP_REPLICATION command failed as there was an error when initializing the group communication layer.
2023-11-24T11:17:50.145Z [container-agent] 
2023-11-24T11:17:50.145Z [container-agent] 





2023-11-24T11:17:50.471Z [container-agent] 2023-11-24 11:17:50 ERROR juju.worker.uniter.operation runhook.go:180 hook "mysql-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
2023-11-24T11:17:50.472Z [container-agent] 2023-11-24 11:17:50 ERROR juju.worker.uniter pebblepoller.go:101 pebble poll failed for container "mysql": failed to send pebble-ready event: hook failed
2023-11-24T11:17:52.052Z [container-agent] 2023-11-24 11:17:52 INFO juju-log Adding pebble layer
2023-11-24T11:17:52.693Z [container-agent] 2023-11-24 11:17:52 INFO juju.worker.uniter.operation runhook.go:186 ran "mysql-pebble-ready" hook (via hook dispatching script: dispatch)
2023-11-24T11:19:01.938Z [container-agent] 2023-11-24 11:19:01 WARNING juju-log No relation: certificates

2023-11-27T02:44:49.452Z [container-agent] 2023-11-27 02:44:49 WARNING juju-log No relation: certificates
2023-11-27T02:44:49.726Z [container-agent] 2023-11-27 02:44:49 INFO juju.worker.uniter.operation runhook.go:186 ran "update-status" hook (via hook dispatching script: dispatch)
```

**Comment by C-Jaewon** [comment]
@kimwnasptd

I proceeded with the installation again from the beginning.

microk8s enable dns ingress metallb:$IPADDR-$IPADDR -> microk8s enable dns hostpath-storage ingress metallb:$IPADDR-$IPADDR

After enabling hostpath-storage, the default value of hostpath-storage was not changed.

Like the image below, the pvc was created, but it works fine without any problems.
![캡처](https://github.com/canonical/bundle-kubeflow/assets/20211880/7b1ade91-f73a-4b43-9cca-c766c21b56aa)

thank you
