### ISSUE TITLE
Admission-webhook failed to start service Error: open /etc/webhook/certs/cert.pem: no such file or directory

### ISSUE THREAD

**Issue by alekseytivonchik** [canonical/bundle-kubeflow#826]
### Bug Description

when creating a Notebook, I get the error:
`statefulset/tst-note-t: create the tst-note-t-0 module in the tst-note-t state set failed error: An internal error occurred: the webhook "admission-webhook" could not be called.kubeflow.org ": failed to call webhook: Post "https://admission-webhook .kubeflow.svc:4443/apply-poddefault?timeout=10 seconds": dial tcp 10.233.59.161:4443: connect: connection denied`
<img width="1497" alt="Снимок экрана 2024-02-13 в 15 28 37" src="https://github.com/canonical/bundle-kubeflow/assets/26677726/da9d32f1-01d5-4c19-ba44-1e721bdd54d4">

### To Reproduce

snap install juju
juju bootstrap my-k8s
juju add-model kubeflow
juju deploy kubeflow --trust

### Environment

K8s: v1.28.6
OS: Ubuntu 22.04
Juju: 3.3.1-genericlinux-amd64

### Relevant Log Output

```shell
kubectl logs admission-webhook-0 -n kubeflow
2024-02-13T11:53:36.729Z [container-agent] 2024-02-13 11:53:36 ERROR juju-log Traceback (most recent call last):
2024-02-13T11:53:36.729Z [container-agent]   File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/charmed_kubeflow_chisme/pebble/_update_layer.py", line 31, in update_layer
2024-02-13T11:53:36.729Z [container-agent]     container.replan()
2024-02-13T11:53:36.729Z [container-agent]   File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/ops/model.py", line 1915, in replan
2024-02-13T11:53:36.729Z [container-agent]     self._pebble.replan_services()
2024-02-13T11:53:36.729Z [container-agent]   File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/ops/pebble.py", line 1680, in replan_services
2024-02-13T11:53:36.729Z [container-agent]     return self._services_action('replan', [], timeout, delay)
2024-02-13T11:53:36.729Z [container-agent]   File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/ops/pebble.py", line 1761, in _services_action
2024-02-13T11:53:36.729Z [container-agent]     raise ChangeError(change.err, change)
2024-02-13T11:53:36.729Z [container-agent] ops.pebble.ChangeError: cannot perform the following tasks:
2024-02-13T11:53:36.729Z [container-agent] - Start service "admission-webhook" (cannot start service: exited quickly with code 255)
2024-02-13T11:53:36.729Z [container-agent] ----- Logs from task 0 -----
2024-02-13T11:53:36.729Z [container-agent] 2024-02-13T11:53:36Z INFO Most recent service output:
2024-02-13T11:53:36.729Z [container-agent]     F0213 11:53:36.706006      14 config.go:46] config=main.Config{CertFile:"/etc/webhook/certs/cert.pem", KeyFile:"/etc/webhook/certs/key.pem"} Error: open /etc/webhook/certs/cert.pem: no such file or directory
2024-02-13T11:53:36.729Z [container-agent] 2024-02-13T11:53:36Z ERROR cannot start service: exited quickly with code 255
```

**Comment by natalytvinova** [comment]
Hitting the same issue

**Comment by Barteus** [comment]
I am hitting the same in the customer's environment.

**Comment by NohaIhab** [comment]
Can you confirm if you see in the juju debug-log the `WARN` log: `Cannot upload certificates to container, deferring`

**Comment by NohaIhab** [comment]
what is the revision of `admission-webhook` in your deployment? @Barteus

**Comment by NohaIhab** [comment]
Can you also provide the logs from the admission-webhook workload container?
with `kubectl logs admission-webhook-0 -n kubeflow -c admission-webhook`
@Barteus @natalytvinova

**Comment by Barteus** [comment]
Admission-webhook logs: https://pastebin.canonical.com/p/JyHD6Mtctp/
Jupyter-controller logs: https://pastebin.canonical.com/p/FBMRGbptyz/
Services in kubeflow ns:
```
$ kubectl get po -n kubeflow
NAME                                             READY   STATUS    RESTARTS        AGE
admission-webhook-0                              2/2     Running   0               4h
argo-controller-0                                2/2     Running   0               25h
dex-auth-0                                       2/2     Running   0               25h
envoy-5fbb9ccbf9-7xhhc                           1/1     Running   0               25h
envoy-operator-0                                 1/1     Running   0               25h
grafana-agent-k8s-0                              2/2     Running   0               25h
istio-ingressgateway-0                           1/1     Running   0               25h
istio-ingressgateway-workload-696584c7c5-2tv9s   1/1     Running   0               25h
istio-pilot-0                                    1/1     Running   0               25h
istiod-7f696dd599-ptkrn                          1/1     Running   0               25h
jupyter-controller-0                             2/2     Running   0               25h
jupyter-ui-0                                     2/2     Running   0               25h
katib-controller-5cc6d58bfd-6k7tw                1/1     Running   0               25h
katib-controller-operator-0                      1/1     Running   0               25h
katib-db-0                                       2/2     Running   0               25h
katib-db-manager-0                               2/2     Running   0               25h
katib-ui-0                                       2/2     Running   3 (23h ago)     25h
kfp-api-0                                        2/2     Running   2 (24h ago)     25h
kfp-db-0                                         2/2     Running   0               25h
kfp-metadata-writer-0                            2/2     Running   0               25h
kfp-persistence-0                                2/2     Running   0               25h
kfp-profile-controller-0                         2/2     Running   0               25h
kfp-schedwf-0                                    2/2     Running   0               25h
kfp-ui-0                                         2/2     Running   1 (24h ago)     25h
kfp-viewer-0                                     2/2     Running   0               25h
kfp-viz-0                                        2/2     Running   2 (2d21h ago)   2d22h
knative-eventing-0                               1/1     Running   0               25h
knative-operator-0                               3/3     Running   0               25h
knative-serving-0                                1/1     Running   1 (24h ago)     25h
kserve-controller-0                              3/3     Running   1 (2d21h ago)   2d22h
kubeflow-dashboard-0                             2/2     Running   0               25h
kubeflow-profiles-0                              3/3     Running   7 (26h ago)     2d22h
kubeflow-roles-0                                 1/1     Running   0               25h
kubeflow-volumes-84f58746bf-rxr68                1/1     Running   0               25h
kubeflow-volumes-operator-0                      1/1     Running   0               25h
metacontroller-operator-0                        1/1     Running   0               25h
metacontroller-operator-charm-0                  1/1     Running   0               25h
minio-0                                          1/1     Running   0               2d22h
minio-operator-0                                 1/1     Running   0               25h
mlflow-mysql-0                                   2/2     Running   0               2d22h
mlflow-server-0                                  3/3     Running   0               25h
mlmd-0                                           1/1     Running   0               2d22h
mlmd-operator-0                                  1/1     Running   0               25h
modeloperator-56c9578cfb-nbrq5                   1/1     Running   0               25h
oidc-gatekeeper-0                                2/2     Running   0               2d22h
pvcviewer-operator-0                             3/3     Running   0               25h
resource-dispatcher-0                            2/2     Running   0               25h
seldon-controller-manager-0                      2/2     Running   4 (2d21h ago)   2d22h
tensorboard-controller-0                         2/2     Running   0               25h
tensorboards-web-app-0                           2/2     Running   0               25h
training-operator-0                              2/2     Running   0               25h

```

**Comment by NohaIhab** [comment]
@Barteus are you able to get the juju debug log for admission webhook from the very beginning?
I need to see which hook failed to execute
the debug logs you've attached are not from when the charm was deployed, you should see there `juju.worker.uniter unit "admission-webhook/0" started`

**Comment by Barteus** [comment]
The status of the charm is:
```
$  juju status admission-webhook
Model     Controller        Cloud/Region  Version  SLA          Timestamp
kubeflow  foundations-maas  ck8s/default  3.1.7    unsupported  14:12:33Z

SAAS        Status  Store             URL
grafana     active  foundations-maas  admin/cos.grafana
loki        active  foundations-maas  admin/cos.loki
prometheus  active  foundations-maas  admin/cos.prometheus

App                Version  Status   Scale  Charm              Channel     Rev  Address        Exposed  Message
admission-webhook           waiting      1  admission-webhook  1.8/stable  275  172.30.181.94  no       waiting for units to settle down

Unit                  Workload     Agent  Address         Ports  Message
admission-webhook/0*  maintenance  idle   10.128.236.170         Workload failed health check
```

To me, it looks like all hooks went ok, and the issue occurred later.
